# Generated by Django 3.2.13 on 2022-05-11 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('publish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('introduction', models.TextField(max_length=2047)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('name', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, verbose_name='Genre Name')),
            ],
        ),
        migrations.CreateModel(
            name='PlayLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RankLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511)),
                ('file_name', models.URLField(blank=True, max_length=511, null=True)),
                ('story', models.TextField(max_length=2047)),
                ('time_played', models.IntegerField()),
                ('time_played_full', models.IntegerField()),
                ('lyric', models.TextField(max_length=2047)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxygen.albums')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxygen.artists')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oxygen.genres')),
            ],
            options={
                'unique_together': {('name', 'artist', 'album')},
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Unknown')], default='N', max_length=2)),
                ('location', models.CharField(choices=[('AH', 'Anhui'), ('BJ', 'Beijing'), ('FJ', 'Fujian'), ('GS', 'Gansu'), ('GD', 'Guangdong'), ('GX', 'Guangxi'), ('GZ', 'Guizhou'), ('HI', 'Hainan'), ('HE', 'Hebei'), ('HA', 'Henan'), ('HL', 'Heilongjiang'), ('HB', 'Hubei'), ('HN', 'Hunan'), ('JL', 'Jilin'), ('JS', 'Jiangsu'), ('JX', 'Jiangxi'), ('LN', 'Liao Ning'), ('NM', 'Inner Mongoria IM'), ('NX', 'Ningxia'), ('QH', 'Qinghai'), ('SD', 'Shandong'), ('SX', 'Shanxi'), ('SN', 'Shaanxi'), ('SH', 'Shanghai'), ('SC', 'Sichuan'), ('TJ', 'Tianjin'), ('XZ', 'Tibet'), ('XJ', 'Xinjiang'), ('YN', 'Yunnan'), ('ZJ', 'Zhejiang'), ('CQ', 'Chongqing'), ('MO', 'Macao'), ('HK', 'Hong Kong'), ('TW', 'Taiwan'), ('++', 'Unknown')], default='++', max_length=20)),
                ('email_address', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('like_songs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oxygen.playlists')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_created=True)),
                ('comment', models.TextField(max_length=2047)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxygen.songs')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oxygen.users')),
            ],
        ),
        migrations.AddField(
            model_name='playlists',
            name='create_usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oxygen.users'),
        ),
        migrations.AddField(
            model_name='genres',
            name='rank_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oxygen.ranklists'),
        ),
        migrations.AddField(
            model_name='albums',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxygen.artists'),
        ),
        migrations.CreateModel(
            name='UserPlaysMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time', models.DateTimeField(auto_now_add=True)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxygen.songs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxygen.users')),
            ],
            options={
                'unique_together': {('user_id', 'song_id')},
            },
        ),
        migrations.CreateModel(
            name='UserLikePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxygen.playlists')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxygen.users')),
            ],
            options={
                'unique_together': {('list_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='UserIsFanOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_created=True)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxygen.artists')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxygen.users')),
            ],
            options={
                'unique_together': {('user_id', 'artist_id')},
            },
        ),
        migrations.CreateModel(
            name='RankListSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_index', models.PositiveIntegerField()),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxygen.ranklists')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxygen.songs')),
            ],
            options={
                'unique_together': {('list_id', 'song_id')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField()),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxygen.playlists')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxygen.songs')),
            ],
            options={
                'unique_together': {('list_id', 'song_id')},
            },
        ),
        migrations.CreateModel(
            name='ArtistInGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single', to='oxygen.artists')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='oxygen.artists')),
            ],
            options={
                'unique_together': {('group_id', 'artist_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='albums',
            unique_together={('name', 'artist')},
        ),
    ]
