# Generated by Django 3.2.13 on 2022-05-03 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('publish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('name', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, verbose_name='Genre Name')),
            ],
        ),
        migrations.CreateModel(
            name='RankLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('genre_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydrogen.genres')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file_name', models.FilePathField(max_length=255)),
                ('length', models.PositiveIntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrogen.albums')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrogen.artists')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydrogen.genres')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('last_login', models.DateTimeField()),
                ('password', models.CharField(max_length=255)),
                ('email_address', models.EmailField(db_index=True, max_length=254, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('comment_date', models.DateField()),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrogen.songs')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydrogen.users')),
            ],
        ),
        migrations.CreateModel(
            name='PlayLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_usr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydrogen.users')),
            ],
        ),
        migrations.AddField(
            model_name='genres',
            name='rank_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hydrogen.ranklists'),
        ),
        migrations.AddField(
            model_name='albums',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrogen.artists'),
        ),
        migrations.CreateModel(
            name='UserPlaysMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time', models.DateTimeField()),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrogen.songs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrogen.users')),
            ],
            options={
                'unique_together': {('user_id', 'song_id')},
            },
        ),
        migrations.CreateModel(
            name='UserLikePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrogen.playlists')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrogen.users')),
            ],
            options={
                'unique_together': {('list_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='RankListSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_index', models.PositiveIntegerField()),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrogen.ranklists')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrogen.songs')),
            ],
            options={
                'unique_together': {('list_id', 'song_id')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField()),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrogen.playlists')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrogen.songs')),
            ],
            options={
                'unique_together': {('list_id', 'song_id')},
            },
        ),
    ]
