# Generated by Django 3.2.13 on 2022-05-03 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydrogen', '0002_alter_users_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistInGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single', to='hydrogen.artists')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='hydrogen.artists')),
            ],
        ),
    ]
