# Generated by Django 3.2.13 on 2022-05-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrogen', '0003_artistingroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranklists',
            name='genre_id',
        ),
        migrations.AlterField(
            model_name='artists',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='songs',
            name='file_name',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='songs',
            name='length',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='songs',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='albums',
            unique_together={('name', 'artist')},
        ),
        migrations.AlterUniqueTogether(
            name='songs',
            unique_together={('name', 'artist', 'album')},
        ),
    ]
